Assignment2/Controllers/EventsDetailsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using olympicEvents.Models;

namespace Assignment2.Controllers
{
    
    public class EventsDetailsController : Controller
    {
        private OlympicEventsModel db = new OlympicEventsModel();

        // GET: EventsDetails
        public ViewResult Index()
        {     
         
            return View(db.EventsDetails);
        }

        // GET: EventsDetails/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EventsDetail eventsDetail = db.EventsDetails.Find(id);
            if (eventsDetail == null)
            {
                return HttpNotFound();
            }
            return View(eventsDetail);
        }
        [Authorize (Roles ="user")]
        // GET: EventsDetails/Create
        public ActionResult Create()
        {
            ViewBag.eventID = new SelectList(db.Events, "eventID", "Name");
            return View();
        }

        // POST: EventsDetails/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "event_detailID,eventID,Name,Description,Age_InYears")] EventsDetail eventsDetail)
        {
            if (ModelState.IsValid)
            {
                db.EventsDetails.Add(eventsDetail);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.eventID = new SelectList(db.Events, "eventID", "Name", eventsDetail.eventID);
            return View(eventsDetail);
        }
        [Authorize(Roles = "user")]
        // GET: EventsDetails/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EventsDetail eventsDetail = db.EventsDetails.Find(id);
            if (eventsDetail == null)
            {
                return HttpNotFound();
            }
            ViewBag.eventID = new SelectList(db.Events, "eventID", "Name", eventsDetail.eventID);
            return View(eventsDetail);
        }

        // POST: EventsDetails/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "event_detailID,eventID,Name,Description,Age_InYears")] EventsDetail eventsDetail)
        {
            if (ModelState.IsValid)
            {
                db.Entry(eventsDetail).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.eventID = new SelectList(db.Events, "eventID", "Name", eventsDetail.eventID);
            return View(eventsDetail);
        }
        [Authorize(Roles = "user")]
        // GET: EventsDetails/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EventsDetail eventsDetail = db.EventsDetails.Find(id);
            if (eventsDetail == null)
            {
                return HttpNotFound();
            }
            return View(eventsDetail);
        }

        // POST: EventsDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            EventsDetail eventsDetail = db.EventsDetails.Find(id);
            db.EventsDetails.Remove(eventsDetail);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Assignment2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <script type = 'text/javascript' >
        var appInsights=window.appInsights||function(config)
        {
            function r(config){ t[config] = function(){ var i = arguments; t.queue.push(function(){ t[config].apply(t, i)})} }
            var t = { config:config},u=document,e=window,o='script',s=u.createElement(o),i,f;for(s.src=config.url||'//az416426.vo.msecnd.net/scripts/a/ai.0.js',u.getElementsByTagName(o)[0].parentNode.appendChild(s),t.cookie=u.cookie,t.queue=[],i=['Event','Exception','Metric','PageView','Trace','Ajax'];i.length;)r('track'+i.pop());return r('setAuthenticatedUserContext'),r('clearAuthenticatedUserContext'),config.disableExceptionTracking||(i='onerror',r('_'+i),f=e[i],e[i]=function(config, r, u, e, o) { var s = f && f(config, r, u, e, o); return s !== !0 && t['_' + i](config, r, u, e, o),s}),t
        }({
            instrumentationKey:'c2fad8ce-66e0-4e6b-a7bd-64e64201b373'
        });
        
        window.appInsights=appInsights;
        appInsights.trackPageView();
    </script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Olympic Events", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Events", "Index", "Events")</li>
                   { 

                    <li>@Html.ActionLink("Event Details","Index", "EventsDetails")</li>
                
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Ramanjeet Singh Student No:200349853</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>